### PR TITLE
* scoop/__main__.py: Catch KeyboardInterrupt exception.

### PR DESCRIPTION
**Pull request by bje-**
This makes SCOOP nice and quiet if the user interrupts a task.

### CODE REVIEW

**Comment by soravux** [comment]
Hello,
On my side, this modification removes the traceback from the launcher, but it still shows the traceback from the workers. Is that the intended behaviour?

On a separate story, is there a use case for suppressing the KeyboardInterrupt traceback?

**Comment by bje-** [comment]
On Tue, Apr 19, 2016 at 08:43:03PM -0700, Yannick Hold wrote:

> On my side, this modification removes the traceback from the
> launcher, but it still shows the traceback from the workers. Is that
> the intended behaviour?

No, I guess not.

> On a separate story, is there a use case for suppressing the
> KeyboardInterrupt traceback?

Yes. Normally when you interrupt a program, you are not interested in
a traceback. You just want it to stop. If you want a traceback, you
can run it under a debugger (or in a debugging mode).  It's ugly as
sin to spit up a traceback in these circumstances.

Ben

**Comment by soravux** [comment]
It is, however, the default behaviour of Python. Suppressing this usual output would cause a surprise to a experimented Python user. I would advise against it as it could provide useful information as to why a particular run has stopped, provided you log your executions (using `tee`, for instance) or where the execution was possibly stuck. As such, unless the default behaviour of Python changes to not show any traceback upon user interruption, I don't think suppressing it for SCOOP executions is a good idea.

However, you discovered a valid issue: there are too many tracebacks displayed at the end of an execution halted by the user, some of them should not be shown to the user. I will correct that in a commit soon.

If you still want to remove the traceback completely, you could do this at the beginning of your code (will work on with any Python code, not only SCOOP):

    import signal
    import os
    def signal_handler(signal, frame):
        os._exit(0)
    signal.signal(signal.SIGINT, signal_handler)

**Comment by soravux** [comment]
I removed the extraneous tracebacks in a576bf121851d91de93c05d077acf8426e099045. Can you confirm it removed all the tracebacks unrelated to the file being executed?

**Pull request closed without merging**
