### PR TITLE
Fix add support for python > 3.10 

### PR DESCRIPTION
**Pull request by asyncmind0**

### CODE REVIEW

**Comment by bje-** [comment]
Can we get this merged soon, please? SCOOP is completely broken on Python 3.10 at present.

**Comment by soravux** [comment]
Apologies for the delay.

**Comment by bje-** [comment]
Thanks! Will you be releasing a new PyPI package as well?

**Comment by soravux** [comment]
Done: https://pypi.org/project/scoop/0.7.2.0/

**Pull request merged**
